// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ieGse5M7Xndm4WzxY8eOpONlMO-tnUM',
    appId: '1:1034984908272:web:43f3d82cfdaa50d565a935',
    messagingSenderId: '1034984908272',
    projectId: 'avellana-268c3',
    authDomain: 'avellana-268c3.firebaseapp.com',
    storageBucket: 'avellana-268c3.firebasestorage.app',
    measurementId: 'G-E2PXS5JZ9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbktZ9ST_-drF5paY6AhY-RVjKdzzagI',
    appId: '1:1034984908272:android:55ac1ebb40bb46fe65a935',
    messagingSenderId: '1034984908272',
    projectId: 'avellana-268c3',
    storageBucket: 'avellana-268c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJJVmV9cKPH5j6c_OGgeZdqFFBaGLsdk',
    appId: '1:1034984908272:ios:e2697afdd6de042765a935',
    messagingSenderId: '1034984908272',
    projectId: 'avellana-268c3',
    storageBucket: 'avellana-268c3.firebasestorage.app',
    iosBundleId: 'com.example.flutterAvellana1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJJVmV9cKPH5j6c_OGgeZdqFFBaGLsdk',
    appId: '1:1034984908272:ios:e2697afdd6de042765a935',
    messagingSenderId: '1034984908272',
    projectId: 'avellana-268c3',
    storageBucket: 'avellana-268c3.firebasestorage.app',
    iosBundleId: 'com.example.flutterAvellana1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ieGse5M7Xndm4WzxY8eOpONlMO-tnUM',
    appId: '1:1034984908272:web:96500f5a7b2210a665a935',
    messagingSenderId: '1034984908272',
    projectId: 'avellana-268c3',
    authDomain: 'avellana-268c3.firebaseapp.com',
    storageBucket: 'avellana-268c3.firebasestorage.app',
    measurementId: 'G-1HZXHEPZR9',
  );
}
